### PR TITLE
Cleanups (including a cleaner implementation for feature flag)

### PR DESCRIPTION
**Pull request by leoetlino**
This change is [Reviewable](https://reviewable.io/reviews/innovate-technologies/control/29)

### CODE REVIEW

**Comment by meyskens** [comment]
Reviewed 9 of 9 files at r1.
Review status: 6 of 16 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/innovate-technologies/control/29)*

**Comment by meyskens** [comment]
Reviewed 10 of 10 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/innovate-technologies/control/29)*

**Comment by leoetlino** [comment]
Do not merge yet. Found an issue with the logout part.

**Comment by leoetlino** [comment]
Added a new commit to make sure Control does not throw an error and stop working when someone messes with the local storage.

**Pull request merged**
