### PR TITLE
[WIP] Add a DJ tab with a status pane

### PR DESCRIPTION
**Pull request by leoetlino**
This adds a DJ tab and a status pane to the page nav.

Still WIP and not working yet.

---

This change is [Reviewable](https://reviewable.io/reviews/innovate-technologies/control/34)

### CODE REVIEW

**Comment by meyskens** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/header-nav.html, line 22 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/control/34#-KDJy9e22vE97TO3FVSt:-KDJy9e3SjEi8dvBtmxt:1087624797) ([raw file](https://github.com/innovate-technologies/control/blob/378cf84328e7bfda33c16f15c9d7ee67cfc84ea3/src/header-nav.html#L22)):*
We should look into adding some font styles not to keep repeating the same icon everywhere

---

*[src/dj/dj-services-service.js, line 32 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/control/34#-KDJyOCqSvj7tcGZ3dYg:-KDJyOCqSvj7tcGZ3dYh:1470581910) ([raw file](https://github.com/innovate-technologies/control/blob/378cf84328e7bfda33c16f15c9d7ee67cfc84ea3/src/dj/dj-services-service.js#L32)):*
We should keep that on Cast as there don't be a separate billed DJ service.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/innovate-technologies/control/34)*

**Comment by meyskens** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/innovate-technologies/control/34)*

**Comment by leoetlino** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/header-nav.html, line 22 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/control/34#-KDJy9e22vE97TO3FVSt:-KDZyKyasWajTdyCzZV4:-365765058) ([raw file](https://github.com/innovate-technologies/control/blob/378cf84328e7bfda33c16f15c9d7ee67cfc84ea3/src/header-nav.html#L22)):*
What icon do you think would work, for DJ?

---

*[src/dj/dj-services-service.js, line 32 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/control/34#-KDJyOCqSvj7tcGZ3dYg:-KDZyVgl04nAM8N_x4Yl:-1483869589) ([raw file](https://github.com/innovate-technologies/control/blob/378cf84328e7bfda33c16f15c9d7ee67cfc84ea3/src/dj/dj-services-service.js#L32)):*
erm, then perhaps we don't need this whole thing. How will ITFrame send DJ services to Control?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/innovate-technologies/control/34)*

**Comment by leoetlino** [comment]
ping

**Comment by meyskens** [comment]
pong: on holiday
pong 2: will quicky answer your burning questions

**Comment by meyskens** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/header-nav.html, line 22 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/control/34#-KDJy9e22vE97TO3FVSt:-KDykP_5xt0sckLi-uV0:586655499) ([raw file](https://github.com/innovate-technologies/control/blob/378cf84328e7bfda33c16f15c9d7ee67cfc84ea3/src/header-nav.html#L22)):*
Was thinking on adding an extra open available icon font using less or more the same style but with more music related. 

---

*[src/dj/dj-services-service.js, line 32 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/control/34#-KDJyOCqSvj7tcGZ3dYg:-KDykXsyFH7FKazkA14e:1526515741) ([raw file](https://github.com/innovate-technologies/control/blob/378cf84328e7bfda33c16f15c9d7ee67cfc84ea3/src/dj/dj-services-service.js#L32)):*
DJ == Cast. Except from the separate routes for media/clock/playlist management Cast and DJ share config files, WHMCS entries and create/delete routes. There is a DJ.enabled tag that starts the container. Was thinking to allow media uploads etc with it even disables since it actually doesn't matter and it provides convinience

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/innovate-technologies/control/34)*

**Comment by leoetlino** [comment]
Review status: 4 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/header-nav.html, line 22 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/control/34#-KDJy9e22vE97TO3FVSt:-KG6nYR6fmjruRYIauo_:-499146009) ([raw file](https://github.com/innovate-technologies/control/blob/378cf84328e7bfda33c16f15c9d7ee67cfc84ea3/src/header-nav.html#L22)):*
Done.

---

*[src/dj/dj-services-service.js, line 32 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/control/34#-KDJyOCqSvj7tcGZ3dYg:-KG6n-x5v8O4EeKyfpdN:-2141594653) ([raw file](https://github.com/innovate-technologies/control/blob/378cf84328e7bfda33c16f15c9d7ee67cfc84ea3/src/dj/dj-services-service.js#L32)):*
so… DJ config is embedded inside Cast, and a DJ service is linked to one and only one Cast service, if I understand correctly. Is that right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/innovate-technologies/control/34)*

**Comment by meyskens** [comment]
Review status: 4 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/dj/dj-services-service.js, line 32 \[r1\]](https://reviewable.io:443/reviews/innovate-technologies/control/34#-KDJyOCqSvj7tcGZ3dYg:-KG84Onk1n4lWvDlra4I:1620071343) ([raw file](https://github.com/innovate-technologies/control/blob/378cf84328e7bfda33c16f15c9d7ee67cfc84ea3/src/dj/dj-services-service.js#L32)):*
Correct. DJ is always with Cast and even share configuration files and billing. ITFrame will add a DJ unit file to the cluster when it noticed the DJ enabled in the config file. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/innovate-technologies/control/34)*

**Comment by leoetlino** [comment]
@meyskens re 8f1b8ad, what do you suggest for the UI on small screens? We're going to need a lot of space (which is why I made the container wider).

**Comment by meyskens** [comment]
@leoetlino can you make this a branch here so I have write access?

**Comment by leoetlino** [comment]
I have rebased this and cleaned up the commits. Feel free to create a PR (on my PR).

**Pull request merged**
